/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportCustomRouteImport } from './routes/support-custom'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ProductsListRouteImport } from './routes/products-list'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as DesingsystemRouteImport } from './routes/desingsystem'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SupportNewRouteImport } from './routes/support/new'
import { Route as SupportNewIndexRouteImport } from './routes/support/new/index'
import { Route as SupportNewCaseIdRouteImport } from './routes/support/new.$caseId'

const SupportCustomRoute = SupportCustomRouteImport.update({
  id: '/support-custom',
  path: '/support-custom',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsListRoute = ProductsListRouteImport.update({
  id: '/products-list',
  path: '/products-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DesingsystemRoute = DesingsystemRouteImport.update({
  id: '/desingsystem',
  path: '/desingsystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const SupportNewRoute = SupportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SupportRoute,
} as any)
const SupportNewIndexRoute = SupportNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportNewRoute,
} as any)
const SupportNewCaseIdRoute = SupportNewCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => SupportNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/desingsystem': typeof DesingsystemRoute
  '/products': typeof ProductsRoute
  '/products-list': typeof ProductsListRoute
  '/support': typeof SupportRouteWithChildren
  '/support-custom': typeof SupportCustomRoute
  '/support/new': typeof SupportNewRouteWithChildren
  '/support/': typeof SupportIndexRoute
  '/support/new/$caseId': typeof SupportNewCaseIdRoute
  '/support/new/': typeof SupportNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/desingsystem': typeof DesingsystemRoute
  '/products': typeof ProductsRoute
  '/products-list': typeof ProductsListRoute
  '/support-custom': typeof SupportCustomRoute
  '/support': typeof SupportIndexRoute
  '/support/new/$caseId': typeof SupportNewCaseIdRoute
  '/support/new': typeof SupportNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/desingsystem': typeof DesingsystemRoute
  '/products': typeof ProductsRoute
  '/products-list': typeof ProductsListRoute
  '/support': typeof SupportRouteWithChildren
  '/support-custom': typeof SupportCustomRoute
  '/support/new': typeof SupportNewRouteWithChildren
  '/support/': typeof SupportIndexRoute
  '/support/new/$caseId': typeof SupportNewCaseIdRoute
  '/support/new/': typeof SupportNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/contact'
    | '/desingsystem'
    | '/products'
    | '/products-list'
    | '/support'
    | '/support-custom'
    | '/support/new'
    | '/support/'
    | '/support/new/$caseId'
    | '/support/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/contact'
    | '/desingsystem'
    | '/products'
    | '/products-list'
    | '/support-custom'
    | '/support'
    | '/support/new/$caseId'
    | '/support/new'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/contact'
    | '/desingsystem'
    | '/products'
    | '/products-list'
    | '/support'
    | '/support-custom'
    | '/support/new'
    | '/support/'
    | '/support/new/$caseId'
    | '/support/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  DesingsystemRoute: typeof DesingsystemRoute
  ProductsRoute: typeof ProductsRoute
  ProductsListRoute: typeof ProductsListRoute
  SupportRoute: typeof SupportRouteWithChildren
  SupportCustomRoute: typeof SupportCustomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-custom': {
      id: '/support-custom'
      path: '/support-custom'
      fullPath: '/support-custom'
      preLoaderRoute: typeof SupportCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-list': {
      id: '/products-list'
      path: '/products-list'
      fullPath: '/products-list'
      preLoaderRoute: typeof ProductsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desingsystem': {
      id: '/desingsystem'
      path: '/desingsystem'
      fullPath: '/desingsystem'
      preLoaderRoute: typeof DesingsystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/new': {
      id: '/support/new'
      path: '/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof SupportNewRouteImport
      parentRoute: typeof SupportRoute
    }
    '/support/new/': {
      id: '/support/new/'
      path: '/'
      fullPath: '/support/new/'
      preLoaderRoute: typeof SupportNewIndexRouteImport
      parentRoute: typeof SupportNewRoute
    }
    '/support/new/$caseId': {
      id: '/support/new/$caseId'
      path: '/$caseId'
      fullPath: '/support/new/$caseId'
      preLoaderRoute: typeof SupportNewCaseIdRouteImport
      parentRoute: typeof SupportNewRoute
    }
  }
}

interface SupportNewRouteChildren {
  SupportNewCaseIdRoute: typeof SupportNewCaseIdRoute
  SupportNewIndexRoute: typeof SupportNewIndexRoute
}

const SupportNewRouteChildren: SupportNewRouteChildren = {
  SupportNewCaseIdRoute: SupportNewCaseIdRoute,
  SupportNewIndexRoute: SupportNewIndexRoute,
}

const SupportNewRouteWithChildren = SupportNewRoute._addFileChildren(
  SupportNewRouteChildren,
)

interface SupportRouteChildren {
  SupportNewRoute: typeof SupportNewRouteWithChildren
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportNewRoute: SupportNewRouteWithChildren,
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  DesingsystemRoute: DesingsystemRoute,
  ProductsRoute: ProductsRoute,
  ProductsListRoute: ProductsListRoute,
  SupportRoute: SupportRouteWithChildren,
  SupportCustomRoute: SupportCustomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
